package com.inmobi.adserve.channels.util;

import java.util.Arrays;
import java.util.List;

public class VelocityTemplateFieldConstants {
    public static final String SDK500_ONWARDS = "SDK500Onwards";
    public static final String IS_DEEPLINK_SUPPORTED = "IS_DEEPLINK_SUPPORTED";
    public static final String ANDROID = "ANDROID";
    public static final String IOS = "IOS";
    public static final String IMAI_BASE_URL = "IMAIBaseUrl";
    public static final String IM_BEACON_URL = "IMBeaconUrl";
    public static final String IM_CLICK_URL = "IMClickUrl";
    public static final String VIEWABILE = "Viewable";
    public static final String VIEWABILITY_TRACKER = "ViewabilityTracker";
    public static final String AUDIENCE_VERIFICATION_TRACKER = "AudienceVerificationTracker";
    public static final String THIRD_PARTY_IMPRESSION_TRACKER = "ThirdPartyImpressionTracker";
    public static final String THIRD_PARTY_CLICK_TRACKER = "ThirdPartyClickTracker";
    public static final String PARTNER_BEACON_URL = "PartnerBeaconUrl";
    public static final String PARTNER_BEACON_LIST = "partnerBeacons";
    public static final String PARTNER_CLICK_URL = "PartnerClickUrl";
    public static final String PARTNER_AD_CLICK_URL = "PartnerAdClickUrl";
    public static final String PARTNER_AD_CLICK_URL1 = "PartnerAdClickUrl1";
    public static final String PARTNER_IMG_URL = "PartnerImgUrl";
    public static final String PARTNER_HTML_CODE = "PartnerHtmlCode";
    public static final String PARTNER_CALL_CLICK_URL1 = "PartnerCallUrl1";
    public static final String PARTNER_LOGO_IMG_URL = "PartnerLogoImgUrl";
    public static final String PARTNER_LOGO_CLICK_URL = "PartnerLogoClickUrl";
    public static final String PARTNER_DISPLAY_URL = "PartnerDisplayUrl";
    public static final String PARTNER_DISPLAY_URL1 = "PartnerDisplayUrl1";
    public static final String PARTNER_DISPLAY_CLICK_URL = "PartnerDisplayClickUrl";
    public static final String PARTNER_DISPLAY_CLICK_URL1 = "PartnerDisplayClickUrl1";
    public static final String PARTNER_CLICK_BEACON = "PartnerClickBeacon";
    public static final String AD_TEXT = "AdText";
    public static final String AD_TEXT1 = "AdText1";
    public static final String DESCRIPTION = "description";
    public static final String DESCRIPTION1 = "description1";
    public static final String TEMPLATE = "Template";
    public static final String SDK = "SDK";
    public static final String SDK360_ONWARDS = "SDK360Onwards";
    public static final String SDK450_ONWARDS = "SDK450Onwards";
    public static final String IS_INTERSTITIAL = "isInterstitial";
    public static final String SPROUT = "Sprout";
    public static final String PARTNER_FAVICON_IMG_URL = "PartnerFaviconImgUrl";
    public static final String PARTNER_FAVICON_IMG_URL1 = "PartnerFaviconImgUrl1";
    public static final List<String> MICROSOFT_PARTNER_IMG_URL = Arrays.asList("PartnerImgUrl", "PartnerCallOrLocationImgUrl");
    public static final List<String> PARTNER_IMG_CLICK_URL = Arrays.asList("PartnerImgIconClickUrl", "PartnerCallOrLocationIconClickUrl");
    public static final List<String> MICROSOFT_PARTNER_IMG_URL1 = Arrays.asList("PartnerImgUrl1", "PartnerCallOrLocationImgUrl1");
    public static final List<String> MICROSOFT_PARTNER_IMG_CLICK_URL1 = Arrays.asList("PartnerImgIconClickUrl1", "PartnerCallOrLocationIconClickUrl1");
    public static final String WIDTH = "width";
    public static final String HEIGHT = "height";
}
