package com.inmobi.castest.casconfenums.def;

public class QueryConf {

    public enum Query {
        SELECT_WAPCHANNEL_ADGROUP_SEGMENT, UPDATE_WAPCHANNEL_ADGROUP_SEGMENT, UPDATE_ALL_WAPCHANNEL_ADGROUP_SEGMENT,
        UPDATE_OTHER_WAPCHANNEL_ADGROUP_SEGMENT, SELECT_WAP_CHANNEL, INSERT_WAP_CHANNEL, UPDATE_WAP_CHANNEL,
        selectRealTimeDcpFeedback, insertRealtimeDcpFeedbackQuery, updateRealtimeDCPFeedbackQuery,
        selectDCPAdvertiserBurnQuery, insertDCPAdvertiserBurnQuery, selectEarningsFeedBackQuery,
        insertEarningsDcpFeedbackQuery, updatEarningsDcpFeedBackQuery, updateAllSites, deleteSiteEcpm,
        insertSiteEcpm, deletePricingEngine, insertPricingEngine, UPDATE_DCP_ADV_BURN_QUERY,
        UPDATE_WAPCHANNEL_ADGROUP_ADGROUPID_FOR_FENDER, INSERT_WAPCHANNEL_ADGROUP_SEGMENT, INSERT_WAP_CHANNEL_AD,
        UPDATE_WAP_CHANNEL_AD, SELECT_WAP_CHANNEL_AD, DELETE_WAPCHANNEL_ADGROUP_SEGMENT, DELETE_MULTI_WAPCHANNEL_ADGROUP_SEGMENT, DELETE_MULTI_WAPCHANNEL_AD, DELETE_WAPCHANNEL_ADGROUP_LIKE_TEST, SELECT_DCP_CHN_SITE_INC_EXC,
        UPDATE_DCP_CHN_SITE_INC_EXC, DELETE_IX_PACKAGES, DELETE_IX_PACKAGE_DEALS, DELETE_TARGETING_SEGMENT, INSERT_IX_PACKAGES, INSERT_TARGETING_SEGMENT,
        INSERT_IX_PACKAGE_DEALS, SELECT_WAP_SITE_UAC, INSERT_WAP_SITE_UAC, DELETE_WAP_SITE_UAC, SELECT_WAP_SITE,
        INSERT_WAP_SITE, DELETE_WAP_SITE,
        INSERT_WAP_PUBLISHER_IX, DELETE_WAP_PUBLISHER_IX
    }


    public enum E2EQuery {
        SELECT_WAP_SITE_SITE_ID, SELECT_WAP_PUBLISHER_ID, UPDATE_WAP_SITE, UPDATE_WAP_PUBLISHER_IX, SELECT_WAP_PUBLISHER_IX, INSEERT_WAP_PUBLISHER_IX, DELETE_SITE_TAGS, INSERT_SITE_TAGS, SELECT_SITE_ADVERTISER_PREFERENCE,
        DELETE_SITE_ADVERTISER_PREFERENCE, SELECT_PLACEMENT_TEMPLATE, UPDATE_PLACEMENT_TEMPLATE, DELETE_SITE_CATEGORY_MANUAL, INSERT_SITE_CATEGORY_MANUAL,
        DELETE_SITE_CATEGORY_OFFFLINE, INSERT_SITE_CATEGORY_OFFFLINE, DELETE_PRICING_REPOSITORY, INSERT_INTO_PRICING_REPOSITORY, DELETE_RULES_REPOSITORY, INSERT_RULES_REPOSITORY, UPDATE_PLACEMENT
    }

}
